apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: NAMESPACE
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 1
       maxUnavailable: 0                  
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: dockerrock123/mongodb-k8s:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: NAMESPACE
  labels:
    app: productpage
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http-productpage
    targetPort: 80
    protocol: TCP
  selector:
    app: productpage